<?php
require_once "view/cls_renderer.php";
require_once "lib/db/DBConn.php";
require_once "lib/core/Constants.php";
require_once "lib/core/strutil.php";
require_once "session_check.php";

class cls_store_featured extends cls_renderer {
    var $currStore;
    var $params;
    function __construct($params=null) {
        $this->currStore = getCurrUser();
        $this->params = $params;
    }
    function extraHeaders() {
        if (!$this->currStore) {
            ?>
<h2>Session Expired</h2>
Your session has expired. Click <a href="">here</a> to login.
            <?php
            return;
        }
        ?>
<link href="css/mb/movingboxes.css" media="screen" rel="stylesheet">
<!--[if lt IE 9]> -->
<link href="css/mb/movingboxes-ie.css" rel="stylesheet" media="screen" />
<script src="js/mb/jquery.movingboxes.js"></script>

<link rel="stylesheet" href="css/prettyPhoto.css" type="text/css" media="screen" title="prettyPhoto main stylesheet" charset="utf-8" />
<script src="js/prettyPhoto/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    <!--//--><![CDATA[//><!--

    $(function(){
        $("a[rel^='prettyPhoto']").prettyPhoto({animation_speed:'fast',slideshow:3000, hideflash: true});
    });

    $(function(){

		$('#slider').movingBoxes({
			/* width and panelWidth options deprecated, but still work to keep the plugin backwards compatible
			width: 500,
			panelWidth: 0.5,
			*/
			startPanel   : 3,      // start with this panel
			wrap         : false,   // if true, the panel will "wrap" (it really rewinds/fast forwards) at the ends
			buildNav     : true,   // if true, navigation links will be added
			navFormatter : function(){ return "&#9679;"; } // function which returns the navigation text for each panel
		});
    });
    //--><!]]>
    
</script>
<style type="text/css">
.ordernow {
	-moz-box-shadow:inset 0px 1px 0px 0px #a4e271;
	-webkit-box-shadow:inset 0px 1px 0px 0px #a4e271;
	box-shadow:inset 0px 1px 0px 0px #a4e271;
	background-color:#89c403;
	-moz-border-radius:6px;
	-webkit-border-radius:6px;
	border-radius:6px;
	border:1px solid #74b807;
	display:inline-block;
	color:#ffffff;
	font-family:arial;
	font-size:15px;
	font-weight:bold;
	padding:6px 24px;
	text-decoration:none;
	text-shadow:1px 1px 0px #528009;
}.ordernow:hover {
	background-color:#77a809;
}.ordernow:active {
	position:relative;
	top:1px;
}
/* This imageless css button was generated by CSSButtonGenerator.com */
</style>
    <?php
    }
    //extra-headers close

    public function pageContent() {
        $menuitem = "storefeature";
        include "sidemenu.".$this->currStore->usertype.".php";
        ?>

<div class="grid_10">
            <?php
            $db = new DBConn();
            $store_id = getCurrUserId();

            //$query = "select * from it_ck_featureddesigns";
            $query = "select fd.*,c.name from it_ck_featureddesigns fd , it_categories c where fd.ctg_id = c.id ";
            $designs = $db->fetchObjectArray ($query);

            ?>
        <div class="grid_6" style="margin-left:50px; margin-top:10px;">
            <h3>Featured Designs</h3>
        </div>
        <br><br></br>
        <div id="wrapper" align="center">
        <br>
        
	<!-- MovingBoxes Slider -->
	<ul id="slider">
            <?php foreach ($designs as $design) { ?>
		<li>
			<a href="images/stock/<?php echo $design->image; ?>" rel="prettyPhoto"><img src="images/stock/<?php echo $design->image; ?>" width="150" alt="" ></a>
			<h5>Design Number :<?php echo $design->design_no;?></h5>
			<p>Category : <?php echo $design->name; ?></p>
                        <p style="margin-top:-10px;"><button class="ordernow" onclick="window.location='store/designs/ctg=<?php echo $design->ctg_id;?>/dno=<?php echo $design->design_no;?>'">Order Now</button></p>
		</li>
            <?php } ?>
	</ul> <!-- end Slider #1 -->
        </div> <!-- end wrapper -->
</div>
    <?php
    }
}
?>